theme: jekyll-theme-chirpy
baseurl: ''
lang: en-US
timezone: Asia/Shanghai
title: NiKoJJ
tagline: Focus on Surveying and Mapping 
description: >-
  Focus on Surveying and Mapping
url: ''
author: NiKoJJ
github:
  username: NiKoJJ
twitter:
  username: NoKoJJ1
social:
  name: NiKoJJ
  email: noel_zjj@163.com
  links:
    - 'https://twitter.com/NoKoJJ1'
    - 'https://github.com/NiKoJJ'
google_site_verification: google_meta_tag_verification
google_analytics:
  id: ''
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false
theme_mode: null
img_cdn: ''
avatar: 'https://cdn.jsdelivr.net/gh/cotes2020/chirpy-images/commons/avatar.jpg'
toc: true
disqus:
  comments: false
  shortname: ''
paginate: 10
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: '/posts/:title/'
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: '/:title/'
      dynamic_title: true
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
      - development
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'
